# Generated by Django 3.2 on 2021-05-03 11:22

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', core.models.RealCharField(max_length=9, unique=True, verbose_name='코드')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('lot_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='지번 주소')),
                ('street_address', models.CharField(max_length=100, verbose_name='도로명 주소')),
                ('detail_address', models.CharField(blank=True, max_length=100, null=True, verbose_name='상세 주소')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='위도')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9, verbose_name='경도')),
                ('rack_cnt', models.IntegerField(verbose_name='거치대 수')),
                ('status', core.models.RealCharField(choices=[('NORMAL', '정상'), ('REPAIR', '수리중'), ('CLOSED', '폐쇄')], default='NORMAL', max_length=6, verbose_name='상태')),
                ('is_lcd', models.BooleanField(blank=True, null=True, verbose_name='LCD 따릉이 거치소 여부')),
            ],
            options={
                'verbose_name': '대여소',
                'verbose_name_plural': '대여소 이름',
                'db_table': 'stations',
            },
        ),
        migrations.CreateModel(
            name='StationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('total_cnt', models.IntegerField(default=0, verbose_name='총 자전거 거치 대수')),
                ('lcd_cnt', models.IntegerField(default=0, verbose_name='qr 자전거 거치 대수')),
                ('qr_cnt', models.IntegerField(default=0, verbose_name='lcd 자전거 거치 대수')),
                ('sprout_cnt', models.IntegerField(default=0, verbose_name='새싹 자전거 거치 대수')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station', verbose_name='대여소')),
            ],
            options={
                'db_table': 'station_logs',
                'ordering': ['created_at'],
            },
        ),
    ]
