# Generated by Django 3.2 on 2021-05-10 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='위도'),
        ),
        migrations.AlterField(
            model_name='station',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=11, verbose_name='경도'),
        ),
        migrations.AlterField(
            model_name='station',
            name='street_address',
            field=models.CharField(max_length=100, null=True, blank=True, verbose_name='도로명 주소'),
        ),
    ]
