# Generated by Django 3.2 on 2021-05-03 11:22

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', core.models.RealCharField(choices=[('BIKE', '자전거'), ('RACK', '거치대'), ('ETC', '기타')], max_length=4, verbose_name='분류')),
                ('description', models.CharField(max_length=2000, verbose_name='상세 내용')),
                ('priority', core.models.RealCharField(choices=[('HIGH', '매우 중요'), ('MID', '중요'), ('LOW', '보통')], max_length=4, verbose_name='우선순위')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station', verbose_name='대여소')),
            ],
            options={
                'verbose_name': '고장 신고',
                'verbose_name_plural': '고장 신고',
                'db_table': 'reports',
            },
        ),
    ]
