# Generated by Django 3.2 on 2021-05-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='해당 지역의 이름을 적어 주세요.', max_length=50, verbose_name='이름')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='설명')),
                ('stations', models.ManyToManyField(to='stations.Station', verbose_name='대여소')),
            ],
            options={
                'verbose_name': '담당지역',
                'verbose_name_plural': '담당지역',
                'db_table': 'sections',
            },
        ),
    ]
